### ISSUE TITLE
looping through packages now deprecated

### ISSUE THREAD

**Issue by SvenBrunk** [OXID-eSales/oxvm_base#24]
https://github.com/OXID-eSales/oxvm_base/blob/df0ccf82aa20573c13a6c5ecc2050ac730cebda0/ansible/roles/server/tasks/main.yml#L45
```
    default: TASK [server : Install System Packages] ****************************************
    default: [DEPRECATION WARNING]: Invoking "apt" only once while using a loop via
    default: squash_actions is deprecated. Instead of using a loop to supply multiple items
    default: and specifying `pkg: {{ item }}`, please use `pkg: [u'curl', u'wget', u'python-
    default: software-properties']` and remove the loop. This feature will be removed in
    default: version 2.11. Deprecation warnings can be disabled by setting
    default: deprecation_warnings=False in ansible.cfg.
    default: changed: [localhost] => (item=[u'curl', u'wget', u'python-software-properties'])
```
There is a nice example how to solve that in an elegant way in:
https://docs.ansible.com/ansible/latest/modules/apt_module.html

```
- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - foo
    - foo-tools
```
Which probably means we only need to change the *following* section to 
```
- name: Install Extra Packages
  become: yes
  apt: pkg={{ server.packages }} state=latest
  when: server.packages
```

**Comment by PirxDanford** [comment]
I pushed the necessary changes to https://github.com/OXID-eSales/oxvm_base/tree/b-solve-issue-24 - needs a review before implementing it :-)

**Comment by PirxDanford** [comment]
I just created a second branch, so we only will have one commit. Thanks for the feedback regarding the state, should be much cleaner now.

https://github.com/OXID-eSales/oxvm_base/compare/b-solve-issue-24-v2

Before merging, could someone please review, try it out and write in here if everything is fine? Thanks!

**Comment by Sieg** [comment]
looks good for me.

**Comment by PirxDanford** [comment]
Merged the branch, the changes have been committed in https://github.com/OXID-eSales/oxvm_base/commit/b1d97c3b869b95d24d2adcb5f63f8f5f9bf6825b
