### ISSUE TITLE
Problem with apache2 instalation while creating new oxvm_base project

### ISSUE THREAD

**Issue by emancypage** [OXID-eSales/oxvm_base#29]
While I try to install the `master` version of the oxvm_base I've got the issue that first firing of the vagrant up not install correctly the apache2 package:

`dpkg: error processing archive /var/cache/apt/archives/apache2_2.4.29-1ubuntu4.7_amd64.deb (--unpack):
 error setting ownership of '/var/www/html.dpkg-new': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/apache2_2.4.29-1ubuntu4.7_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)`

I am using Linux Ubuntu 18.04 LTS (as host).
The problem doesn't occur in Windows 10 (as host).

Solution is that you should add the `html` directory inside `www/` . 
Now the installation process finish correct.

Please fix this and add `html` directory inside `www/`.

**Comment by PirxDanford** [comment]
Hello @emancypage, please retry with the latest version from the master branch. Make sure it contains the commit https://github.com/OXID-eSales/oxvm_base/commit/9de05867fdce64fcb0d4ddf36fd3e89706ca88d8.

Thank you for your report and please let us know if the problem still exists.

**Comment by emancypage** [comment]
Problem still occur. I double check version of the installed oxvm_base. It contains your fixes from mentioned commit. 

The problem occur while default task starts for Apache (still the same as before):

Full debug from CLI:

`default: TASK [apache : Install Apache] *************************************************
    default: fatal: [localhost]: FAILED! => {"cache_update_time": 1563551350, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'apache2'' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "rc": 100, "stderr": "E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr_lines": ["E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following additional packages will be installed:\n  apache2-bin apache2-data apache2-utils libapr1 libaprutil1\n  libaprutil1-dbd-sqlite3 libaprutil1-ldap liblua5.2-0 ssl-cert\nSuggested packages:\n  www-browser apache2-doc apache2-suexec-pristine | apache2-suexec-custom\n  openssl-blacklist\nThe following NEW packages will be installed:\n  apache2 apache2-bin apache2-data apache2-utils libapr1 libaprutil1\n  libaprutil1-dbd-sqlite3 libaprutil1-ldap liblua5.2-0 ssl-cert\n0 upgraded, 10 newly installed, 0 to remove and 55 not upgraded.\nNeed to get 1729 kB of archives.\nAfter this operation, 6985 kB of additional disk space will be used.\nGet:1 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 libapr1 amd64 1.6.3-2 [90.9 kB]\nGet:2 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 libaprutil1 amd64 1.6.1-2 [84.4 kB]\nGet:3 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 libaprutil1-dbd-sqlite3 amd64 1.6.1-2 [10.6 kB]\nGet:4 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 libaprutil1-ldap amd64 1.6.1-2 [8764 B]\nGet:5 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 liblua5.2-0 amd64 5.2.4-1.1build1 [108 kB]\nGet:6 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 apache2-bin amd64 2.4.29-1ubuntu4.8 [1072 kB]\nGet:7 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 apache2-utils amd64 2.4.29-1ubuntu4.8 [82.9 kB]\nGet:8 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 apache2-data all 2.4.29-1ubuntu4.8 [160 kB]\nGet:9 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 apache2 amd64 2.4.29-1ubuntu4.8 [95.1 kB]\nGet:10 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 ssl-cert all 1.0.39 [17.0 kB]\nPreconfiguring packages ...\nFetched 1729 kB in 2s (799 kB/s)\nSelecting previously unselected package libapr1:amd64.\r\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 48325 files and directories currently installed.)\r\nPreparing to unpack .../0-libapr1_1.6.3-2_amd64.deb ...\r\nUnpacking libapr1:amd64 (1.6.3-2) ...\r\nSelecting previously unselected package libaprutil1:amd64.\r\nPreparing to unpack .../1-libaprutil1_1.6.1-2_amd64.deb ...\r\nUnpacking libaprutil1:amd64 (1.6.1-2) ...\r\nSelecting previously unselected package libaprutil1-dbd-sqlite3:amd64.\r\nPreparing to unpack .../2-libaprutil1-dbd-sqlite3_1.6.1-2_amd64.deb ...\r\nUnpacking libaprutil1-dbd-sqlite3:amd64 (1.6.1-2) ...\r\nSelecting previously unselected package libaprutil1-ldap:amd64.\r\nPreparing to unpack .../3-libaprutil1-ldap_1.6.1-2_amd64.deb ...\r\nUnpacking libaprutil1-ldap:amd64 (1.6.1-2) ...\r\nSelecting previously unselected package liblua5.2-0:amd64.\r\nPreparing to unpack .../4-liblua5.2-0_5.2.4-1.1build1_amd64.deb ...\r\nUnpacking liblua5.2-0:amd64 (5.2.4-1.1build1) ...\r\nSelecting previously unselected package apache2-bin.\r\nPreparing to unpack .../5-apache2-bin_2.4.29-1ubuntu4.8_amd64.deb ...\r\nUnpacking apache2-bin (2.4.29-1ubuntu4.8) ...\r\nSelecting previously unselected package apache2-utils.\r\nPreparing to unpack .../6-apache2-utils_2.4.29-1ubuntu4.8_amd64.deb ...\r\nUnpacking apache2-utils (2.4.29-1ubuntu4.8) ...\r\nSelecting previously unselected package apache2-data.\r\nPreparing to unpack .../7-apache2-data_2.4.29-1ubuntu4.8_all.deb ...\r\nUnpacking apache2-data (2.4.29-1ubuntu4.8) ...\r\nSelecting previously unselected package apache2.\r\nPreparing to unpack .../8-apache2_2.4.29-1ubuntu4.8_amd64.deb ...\r\nUnpacking apache2 (2.4.29-1ubuntu4.8) ...\r\ndpkg: error processing archive /tmp/apt-dpkg-install-v7n5l9/8-apache2_2.4.29-1ubuntu4.8_amd64.deb (--unpack):\r\n error setting ownership of '/var/www/html.dpkg-new': Operation not permitted\r\nSelecting previously unselected package ssl-cert.\r\nPreparing to unpack .../9-ssl-cert_1.0.39_all.deb ...\r\nUnpacking ssl-cert (1.0.39) ...\r\nErrors were encountered while processing:\r\n /tmp/apt-dpkg-install-v7n5l9/8-apache2_2.4.29-1ubuntu4.8_amd64.deb\r\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following additional packages will be installed:", "  apache2-bin apache2-data apache2-utils libapr1 libaprutil1", "  libaprutil1-dbd-sqlite3 libaprutil1-ldap liblua5.2-0 ssl-cert", "Suggested packages:", "  www-browser apache2-doc apache2-suexec-pristine | apache2-suexec-custom", "  openssl-blacklist", "The following NEW packages will be installed:", "  apache2 apache2-bin apache2-data apache2-utils libapr1 libaprutil1", "  libaprutil1-dbd-sqlite3 libaprutil1-ldap liblua5.2-0 ssl-cert", "0 upgraded, 10 newly installed, 0 to remove and 55 not upgraded.", "Need to get 1729 kB of archives.", "After this operation, 6985 kB of additional disk space will be used.", "Get:1 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 libapr1 amd64 1.6.3-2 [90.9 kB]", "Get:2 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 libaprutil1 amd64 1.6.1-2 [84.4 kB]", "Get:3 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 libaprutil1-dbd-sqlite3 amd64 1.6.1-2 [10.6 kB]", "Get:4 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 libaprutil1-ldap amd64 1.6.1-2 [8764 B]", "Get:5 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 liblua5.2-0 amd64 5.2.4-1.1build1 [108 kB]", "Get:6 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 apache2-bin amd64 2.4.29-1ubuntu4.8 [1072 kB]", "Get:7 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 apache2-utils amd64 2.4.29-1ubuntu4.8 [82.9 kB]", "Get:8 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 apache2-data all 2.4.29-1ubuntu4.8 [160 kB]", "Get:9 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 apache2 amd64 2.4.29-1ubuntu4.8 [95.1 kB]", "Get:10 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 ssl-cert all 1.0.39 [17.0 kB]", "Preconfiguring packages ...", "Fetched 1729 kB in 2s (799 kB/s)", "Selecting previously unselected package libapr1:amd64.", "(Reading database ... ", "(Reading database ... 5%", "(Reading database ... 10%", "(Reading database ... 15%", "(Reading database ... 20%", "(Reading database ... 25%", "(Reading database ... 30%", "(Reading database ... 35%", "(Reading database ... 40%", "(Reading database ... 45%", "(Reading database ... 50%", "(Reading database ... 55%", "(Reading database ... 60%", "(Reading database ... 65%", "(Reading database ... 70%", "(Reading database ... 75%", "(Reading database ... 80%", "(Reading database ... 85%", "(Reading database ... 90%", "(Reading database ... 95%", "(Reading database ... 100%", "(Reading database ... 48325 files and directories currently installed.)", "Preparing to unpack .../0-libapr1_1.6.3-2_amd64.deb ...", "Unpacking libapr1:amd64 (1.6.3-2) ...", "Selecting previously unselected package libaprutil1:amd64.", "Preparing to unpack .../1-libaprutil1_1.6.1-2_amd64.deb ...", "Unpacking libaprutil1:amd64 (1.6.1-2) ...", "Selecting previously unselected package libaprutil1-dbd-sqlite3:amd64.", "Preparing to unpack .../2-libaprutil1-dbd-sqlite3_1.6.1-2_amd64.deb ...", "Unpacking libaprutil1-dbd-sqlite3:amd64 (1.6.1-2) ...", "Selecting previously unselected package libaprutil1-ldap:amd64.", "Preparing to unpack .../3-libaprutil1-ldap_1.6.1-2_amd64.deb ...", "Unpacking libaprutil1-ldap:amd64 (1.6.1-2) ...", "Selecting previously unselected package liblua5.2-0:amd64.", "Preparing to unpack .../4-liblua5.2-0_5.2.4-1.1build1_amd64.deb ...", "Unpacking liblua5.2-0:amd64 (5.2.4-1.1build1) ...", "Selecting previously unselected package apache2-bin.", "Preparing to unpack .../5-apache2-bin_2.4.29-1ubuntu4.8_amd64.deb ...", "Unpacking apache2-bin (2.4.29-1ubuntu4.8) ...", "Selecting previously unselected package apache2-utils.", "Preparing to unpack .../6-apache2-utils_2.4.29-1ubuntu4.8_amd64.deb ...", "Unpacking apache2-utils (2.4.29-1ubuntu4.8) ...", "Selecting previously unselected package apache2-data.", "Preparing to unpack .../7-apache2-data_2.4.29-1ubuntu4.8_all.deb ...", "Unpacking apache2-data (2.4.29-1ubuntu4.8) ...", "Selecting previously unselected package apache2.", "Preparing to unpack .../8-apache2_2.4.29-1ubuntu4.8_amd64.deb ...", "Unpacking apache2 (2.4.29-1ubuntu4.8) ...", "dpkg: error processing archive /tmp/apt-dpkg-install-v7n5l9/8-apache2_2.4.29-1ubuntu4.8_amd64.deb (--unpack):", " error setting ownership of '/var/www/html.dpkg-new': Operation not permitted", "Selecting previously unselected package ssl-cert.", "Preparing to unpack .../9-ssl-cert_1.0.39_all.deb ...", "Unpacking ssl-cert (1.0.39) ...", "Errors were encountered while processing:", " /tmp/apt-dpkg-install-v7n5l9/8-apache2_2.4.29-1ubuntu4.8_amd64.deb"]}`

**Comment by PirxDanford** [comment]
Thank you for providing the necessary information of how to reproduce this via chat @emancypage.
The commit https://github.com/OXID-eSales/oxvm_base/commit/c3312616701ae53027ef542215f939185159e2d7 should solve it and will be included in a future release.

This issue appears if using NFS with Virtualbox on a Linux hostmachine.

For those affected there are 3 solutions until the next version is released:
1) create the html directory in www manually
2) use the latest version of the master branch of oxvm_base
3) do not use NFS
