### ISSUE TITLE
phpversionformer line ending problem

### ISSUE THREAD

**Issue by masphistaempfli** [OXID-eSales/oxvm_base#4]
I just cloned oxvm_base and started it with an overriden PHP version, to enforce installation of PHPBrew (5.5, personal.yml attachted as txt:[personal.yml.txt](https://github.com/OXID-eSales/oxvm_base/files/297454/personal.yml.txt) )

during provisioning, building php failed with the message:

> ==> default: TASK [php : Check if required php version is already installed] ****************
> ==> default: fatal: [localhost]: FAILED! => {"changed": true, "cmd": "phpbrew list | grep `phpversionformer 5.5`", "delta": "0:00:00.102919", "end": "2016-06-03 13:30:37.105697", "failed": true, "rc": 2, "start": "2016-06-03 13:30:37.002778", "stderr": "/bin/sh: 1: phpversionformer: not found\nUsage: grep [OPTION]... PATTERN [FILE]...\nTry 'grep --help' for more information.", "stdout": "", "stdout_lines": [], "warnings": []}
> ==> default: ...ignoring
> ==> default:
> ==> default: TASK [php : Build PHP version] *************************************************
> ==> default: fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/phpbuild 5.5", "delta": "0:00:00.004753", "end": "2016-06-03 13:30:37.309823", "failed": true, "rc": 1, "start": "2016-06-03 13:30:37.305070", "stderr": "/usr/local/bin/phpbuild: /usr/local/bin/phpversionformer: /bin/bash^M: bad interpreter: No such file or directory", "stdout": "Usage: phpbuild [version] [package_path]\nTo get a list of all available versions use 'phpbrew known' command.\nIf not package path is given, package will not be generated.", "stdout_lines": ["Usage: phpbuild [version] [package_path]", "To get a list of all available versions use 'phpbrew known' command.", "If not package path is given, package will not be generated."], "warnings": []}

I was able to hunt the issue down to `/usr/local/bin/phpversionformer`. When calling it via ssh, it fails with message:
> -bash: /usr/local/bin/phpversionformer: /bin/bash^M: bad interpreter: No such file or directory

The line endings are written as `\r\n` (CRLF), which causes the problem.
When converting to simple `\n` (LF), phpversionformer works.

**Comment by rezonanc-oxid** [comment]
I've tested this on https://github.com/OXID-eSales/oxvm_base/commit/2e13029d07a7e8ec0bfa3c1ffd42fa53ce92ba83 and by running `cat -e /usr/local/bin/phpversionformer` I've received:

```bash
#!/bin/bash$
$
WANTED_VERSION=$1;$
$
...
```

Which means that the file has (LF) line endings.

Also I've tried to look into the history of this file within the repository: https://github.com/OXID-eSales/oxvm_base/commits/master/ansible/roles/php/templates/phpversionformer

History does not reveal that there was a commit which changed line-endings.

My only guess is that you were using this from Windows environment and your git client cloned out the repository with CRLF line endings of the shell templates.

Could you describe what kind of host environment you were using at that time?

**Comment by masphistaempfli** [comment]
You are right, I was using a Windows 7 host. git-bash converted the line endings while cloning.

Maybe you could add a .gitattributes file to force LF line endings for the *.sh files.

**Comment by rezonanc-oxid** [comment]
Strange, as it already has https://github.com/OXID-eSales/oxvm_base/blob/master/.gitattributes in the repository available.

Any ideas why it might have been ignored?

**Comment by masphistaempfli** [comment]
I checked it locally. Problem is, that the gitattributes use LF for `*.*` files. The template has no extension (`phpversionformer`), so the `text=auto` setting appies.

Suggest to change to:
`* text=auto eol=lf`

**Comment by rezonanc-oxid** [comment]
The following changes were made:

* [Updated oxvm_base](https://github.com/OXID-eSales/oxvm_base/commit/ae8539dd7fabb8b98ab4dd00d6df36e867db6302)
* [Updated oxvm_eshop](https://github.com/OXID-eSales/oxvm_eshop/commit/1450d4565be884b73035f8da1a1e79da204e41c4)
* [oxvm_eshop uses the updated base_vm](https://github.com/OXID-eSales/oxvm_eshop/commit/d413e4807523dcc0d2deea73850de74d766db31f)

Can we agree that the issue has been solved?

**Comment by masphistaempfli** [comment]
I tested it.
Works now. Closing the issue

**Comment by rezonanc-oxid** [comment]
Thanks!
